apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secret-store
spec:
  provider:
    pulumi:
      organization: dirien
      environment: 01-idp-dev
      project: next-level-powers-enhance-your-idp-with-the-wasm-and-dapr-hero-team-up
      accessToken:
        secretRef:
          name: pulumi-access-token
          key: PULUMI_ACCESS_TOKEN
          namespace: default
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: db-secret-store
spec:
  provider:
    pulumi:
      organization: dirien
      environment: db
      project: next-level-powers-enhance-your-idp-with-the-wasm-and-dapr-hero-team-up
      accessToken:
        secretRef:
          name: pulumi-access-token
          key: PULUMI_ACCESS_TOKEN
          namespace: default
